@startuml Взаимодействие модулей
package "Веб-интерфейс" {
  [Редактирование товаров]
  [Формирование отчетности]
  [Личный кабинет партнера]
}

package "API для партнеров" {
  [Получение списка товаров]
}

package "Внутренний API" {
  [API для управления товарами]
  [API для управления заказами.]
  [API для аналитики]
  [API для управления доставками]
  [API для управления возвратами]
}

package "База данных" {
  [Товары]
  [Заказы]
  [Расчеты с маркетплейсами]
  [Доставки]
  [ОВХ]
  [Цены]
  [Маркетплейсы]
}

package "Интеграционные модули" {
  [Сбор данных из маркетплейсов]
  [Сбор данных из 1С]
  [Сбор данных со служб доставки]
}

package "Аналитический модуль" {
  [Рентабельность]
  [ABC-анализ]
  [Прибыль-убытки]
  [Прочие аналитические отчеты]
}

package "Планировщик задач" {
  [Периодический импорт данных]
}

[Редактирование товаров] <--> [Товары]
[Формирование отчетности] --> [Аналитический модуль]
[База данных] --> [Получение списка товаров]
[Сбор данных из маркетплейсов] --> [База данных]
[Сбор данных из 1С] --> [База данных]
[Сбор данных со служб доставки] --> [База данных]
[Рентабельность]  --> [База данных]
[ABC-анализ] --> [База данных]
[Внутренний API] <--> [База данных]
[База данных] <-- [Прибыль-убытки]
[Периодический импорт данных] <--> [Сбор данных из маркетплейсов]
[Периодический импорт данных] <--> [Сбор данных со служб доставки]
[Периодический импорт данных] <--> [Сбор данных из 1С]
@enduml